Feature/#001
ColaboAI/ColaboAI-web_v1 pull request #3
Opened 2022-07-22 07:37 UTC by sgeunhi

2022-07-23 11:30 UTC, GoGiants1 requested changes
![스크린샷 2022-07-23 오후 8 20 52](https://user-images.githubusercontent.com/69342392/180603115-40d5e9cf-8799-49b8-9c27-5aee53a5490e.png)

![image](https://user-images.githubusercontent.com/69342392/180603137-bffab60f-b03f-4dfe-8ef8-a31f685b71b1.png)


글꼴 관련 오류가 나네요. 확인부탁드려요.

2022-07-23 11:30 UTC, GoGiants1 commented on pages/favorites.tsx
> +};
함수 내부에 구현하지 않고 이렇게 따로 빼둔 이유가 무엇 때문인가요?

2022-07-23 11:30 UTC, GoGiants1 commented on pages/favorites.tsx
> +    </div>
이쪽에서 공백이랑 `'` 문자 prettier 오류 납니다. webstorm에서 제대로 prettier, eslint 적용되었는지 확인해주세요.

그리고 커밋 전에 `yarn lint` 강제할 수 있게 [가이드](https://prettier.io/docs/en/precommit.html) 보고 설정 부탁드려요!

2022-07-23 11:30 UTC, GoGiants1 commented on pages/search.tsx
> +};
여기도 이렇게 구현되어 있네요.

2022-07-23 11:30 UTC, GoGiants1 commented on styles/header.module.scss
> +}
[stylelint](https://prettier.io/docs/en/integrating-with-linters.html)도 설정하면 좋겠습니다.

2022-07-25 01:26 UTC, sgeunhi commented on pages/favorites.tsx
> +};
재사용되는 레이아웃이라 getLayout을 통해 구현했습니다. [공식문서](https://nextjs.org/docs/basic-features/layouts)를 참고하였습니다.

2022-07-25 01:26 UTC, sgeunhi commented on pages/search.tsx
> +};
재사용되는 레이아웃이라 getLayout을 통해 구현했습니다. [공식문서](https://nextjs.org/docs/basic-features/layouts)를 참고하였습니다.

2022-07-25 01:46 UTC, sgeunhi commented on pages/favorites.tsx
> +};
글꼴 오류 해결했습니다.

2022-07-25 04:50 UTC, sgeunhi commented on pages/favorites.tsx
> +    </div>
수정 완료했습니다.

2022-07-25 04:50 UTC, sgeunhi commented on styles/header.module.scss
> +}
추후 설정하겠습니다.

2022-07-25 05:13 UTC, GoGiants1 approved these changes
LGTM :) 
테스팅 추가하면 완벽!

2022-07-25 05:14 UTC, merged

2022-07-25 05:37 UTC, sgeunhi commented
Fixes #1

2022-07-25 05:40 UTC, sgeunhi commented
Fixes #2